CREATE TABLE BENEFICIO (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  VALOR DECIMAL(15,2) NOT NULL,
  ATIVO BOOLEAN DEFAULT TRUE,
  VERSION BIGINT DEFAULT 0
);

CREATE TABLE TRANSFERENCIA_AUDITORIA (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FROM_ID BIGINT NOT NULL,
  TO_ID BIGINT NOT NULL,
  FROM_NOME VARCHAR(100) NOT NULL,
  TO_NOME VARCHAR(100) NOT NULL,
  AMOUNT DECIMAL(15,2) NOT NULL,
  CREATED_AT TIMESTAMPTZ NOT NULL,
  STATUS VARCHAR(10) NOT NULL,
  DETALHE VARCHAR(255)
);
